accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile/', views.profile, name="profile"),
    path('profile/<int:pk>/update/', views.profile_update, name='profile_update'),
    path('register/', views.register, name="register")
]

blog/urls.py
from django.urls import path
from  . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('post/<int:pk>/<slug:slug>/', views.ArticleDetailView.as_view(), name='detail'),
   # path('post/create/', views.BlogCreateView.as_view(), name='create'),
    path('post/create/', views.create_post, name='create'),
    path('post/<int:pk>/<slug:slug>/update/', views.PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('sm/admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile', default='default_dp.jpeg')


    def __str__(self):
        return self.user.username
    

blog/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Article(models.Model):
    title = models.CharField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)
    content = RichTextField()
    pub_date = models.DateField(auto_now=True)
    publish = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("blog:home")
    
        
    
    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile


class UserRegistrationForm(UserCreationForm, ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username','password1', 'password2']


class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image']


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username']

blog/forms.py
from django.forms import ModelForm
from django.forms.widgets import TextInput, Textarea
from .models import Article



class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'publish']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Post Title'}),
            'content': Textarea(attrs={'placeholder': 'Post Content', 'cols':100, 'rows':100}),
        }
        labels = {
            'title': '',
            'content': '',
        }
        

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, ProfileUpdateForm, UserUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


@login_required
def profile(request):
    template_name = 'accounts/profile.html'
    context = {

    }
    return render(request, template_name, context)

def register(request):
    if request.user.is_authenticated:
        return redirect('blog:home')
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created, Login!')
            return redirect('login')
    template_name = 'accounts/register.html'
    form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, template_name, context)

@login_required
def profile_update(request, pk):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST,instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            
            messages.success(request, 'Profile updated successfully')
            return redirect('profile')
    
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': user_form,
        'p_form': profile_form
    }
    template_name = 'accounts/profile_update.html'
    return render(request, template_name, context)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.utils.text import slugify
from django.views import generic
from .models import Article
from .forms import ArticleForm

class IndexView(generic.ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'

    def get_queryset(self): 
        articles = Article.objects.filter(publish=True)[:5]
        return articles


class ArticleDetailView(generic.DetailView):
    template_name = 'blog/detail.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'title'
        return context
    

@login_required
def create_post(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            #get logged in user
            post_author =  request.user
            #slugify post title
            post_title = slugify(form.cleaned_data.get('title'))
            # save the post without commiting to db
            post = form.save(commit=False)

            # assign to post Article model
            post.slug = post_title
            post.author = post_author
            # save the post
            post.save()
            messages.success(request, 'Your Post Has been created!')
            return redirect('blog:home')

    else:
        form = ArticleForm()

    context = {
        'form': form,
    }
    template_name = 'blog/create_post.html'
    return render(request, template_name, context)
    
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/create_post.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
           return True
        else:
            return False
    
     

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Article
    success_url = '/'
    template_name = 'blog/delete_post.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
           return True
        else:
            return False

accounts/templates/accounts/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">

    <div class="mt-5 mb-5 text-center w-50 centered">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy}}
            <input type="submit" value="Login" class="btn btn-info">
        </form>

        <div>
         <p class="text-muted">Don't have an account? <a href="{% url 'register' %}">Register</a></p>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
        
                <div class="card my-2 shadow-md">
                    <div class="card-body centered">
                        
                            <img src="{{user.profile.profile_image.url}}" class="rounded-circle dp " alt=" {{user.username}}">
                        
                            <p class="card-text">Username: <span class="font-italic text-black-50">{{user.username}}</span></p>
                            <p class="card-text">Email: <span class="font-italic text-black-50">{{user.email}}</span></p>
                       
                    
                </div>
                <a href="{% url 'profile_update' user.id %}" class="btn btn-primary">Update</a>
        </div>
      
    </div



    <div class="col-xs-7">
        
    </div>
    
</div>

{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">

    <div class="mt-5 mb-5 text-center w-50 centered">
        <form action="{% url 'profile_update' user.id %}" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
           {{ u_form|crispy}}
           {{ p_form|crispy}}
            <input type="submit" value="Update" class="btn btn-info">
        </form>

    </div>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">

    <div class="mt-5 mb-5 text-center w-50 centered">
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
           {{ form|crispy}}
            <input type="submit" value="Sign Up" class="btn btn-info">
        </form>

        <div>
         <p class="text-muted"> Already have an account? <a href="{% url 'login'%}">Login</a></p>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">


    {% if title %}
        <title>{{ article.title }}</title>
    {% else %}
      <title>Simple Blog | Home</title>
    {% endif %}
  
</head>
<body>
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-dark">

  <!-- Links -->
  <ul class="navbar-nav mx-auto">
    <li class="nav-item">
      <a class="nav-link font-weight-bold" href="{% url 'blog:home'%}">Simple Blog</a>
    </li>
    <div class="ml-5"></div>

    {% if user.is_authenticated %}
     <li class="nav-item">
      <a class="nav-link" href="{% url 'blog:create'%}">New Post</a>
    </li>
     <li class="nav-item">
      <a class="nav-link" href="{% url 'profile'%}">Profile</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'logout'%}">Logout</a>
    </li>
    {% else %}
     <li class="nav-item">
      <a class="nav-link" href="{% url 'login'%}">Login</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'register'%}">Register</a>
    </li>
    {% endif %}
  </ul>

</nav>
<div class="container">
{% for message in messages %}
  <div class="alert alert-{{ message.tags}} text-center">
    <p>{{ message }}</p>
  </div>
{% endfor %}
      {% block content %}

  {% endblock content %}
</div>


<footer class="mt-5 border-top">
  <div class="text-center p-2">
    <p class="text-black-50">Copyright &copy; 2020, Hopson Gausi. All rights reserved.</p>
  </div>
</footer>

  <!-- Jquery js-->
    <script src="{% static 'blog/js/jquery/jquery-3.5.1.js' %}"></script>
    <!-- Bootstrap js-->
    <script src="{% static 'blog/js/bootstrap.min.js'%}"></script>
</body>
</html>

blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">

    <div class="mt-5 mb-5 text-center w-50 centered">
    <legend><h1>Create New Post</h1></legend>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy}}
            <input type="submit" value="Post" class="btn btn-info">
        </form>

    </div>
</div>

{% endblock content %}

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">

    <div class="mt-5 mb-5 text-center w-50 centered">
    <legend><h1 class="bg-info">Delete Post</h1></legend>
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete <span class="bold">{{ object.title }}</span>?</p>
            <input type="submit" value="Yes, Delete" class="btn btn-danger">
            <a href="{% url 'blog:detail' object.id object.slug %}" class="btn btn-info">No, go back</a>
        </form>
    </div>
</div>

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}


 {% block content %}

<div class="container-fluid text-center">
  <div class="row">
    <div class="col-md-6 mx-auto">
            <div class="card my-2 shadow-md">
                <div class="card-body">
                     <h2 class="card-title">{{ article.title }}</h2>
                     {% if user.is_authenticated and request.user == article.author%}
                     <div>
                      <a href="{% url 'blog:update' object.id object.slug %}" class="btn btn-primary">Update</a>
                      <a href="{% url 'blog:delete' object.id object.slug %}" class="btn btn-danger">Delete</a>
                     </div>
                     {% endif %}
                     <hr>
                     <p class="text-muted small">{{ article.author}} | {{ article.pub_date}}</p>
                    <p class="card-text">{{ article.content|safe}}</p>
                    <a href="{% url 'blog:home'%}" class="card-link small">Go back</a>
                </div>
            </div>
    </div>
    
  </div>
</div>
  
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}


 {% block content %}

<div class="container-fluid text-center m-auto">
  <div class="row">
    <div class="col-md-8 mx-auto">
     {% for article in articles %}
            <div class="card my-2 shadow-md">
                <div class="card-body">
                    <h3 class="card-title">{{ article.title }}</h3><hr>
                    <p class="text-muted small">{{ article.author}} | {{ article.pub_date}}</p>
                    <p class="card-text">{{ article.content|truncatewords:'12'|safe}}</p>
                    <a href="{% url 'blog:detail' article.id article.slug %}" class="card-link small">Read more</a>
                </div>
            </div>
         {% endfor %}
    </div>
    
  </div>
</div>
  
{% endblock content %}
   